### ISSUE TITLE
Gym request: 'Sodini Parklet' (id 467522)

### ISSUE THREAD

**Issue by pgp-issues** [Googer/PgP-Data#26]
Request from Tonatale | 38:

Potential EX Raid location - This gym is located in a park.

**Comment by Googer** [comment]
This is indeed in a parklet according to OSM even, but I'm hesistant to mark it as such manually since looking at its revision history on OSM, it was only marked as one quite recently (September), which is after what's considered to be the current cutoff date / snapshot of OSM data that Niantic is using for Pokemon GO (considered to be sometime in August as of this time).
